name: Build
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
      build-args:
        required: true
        type: string
      artifact:
        required: false
        type: string

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR dev
        uses: docker/login-action@v2
        with:
          registry: upplydev.azurecr.io
          username: upplydev
          password: ${{ secrets.UPPLY_ACR_DEV_PASSWORD }}

      - name: Login to ACR quality
        uses: docker/login-action@v2
        with:
          registry: upplyquality.azurecr.io
          username: upplyquality
          password: ${{ secrets.UPPLY_ACR_QUALITY_PASSWORD }}

      - name: Login to ACR preprod
        uses: docker/login-action@v2
        with:
          registry: upplypreprod.azurecr.io
          username: upplypreprod
          password: ${{ secrets.UPPLY_ACR_PREPROD_PASSWORD }}

      - name: Login to ACR prod
        uses: docker/login-action@v2
        with:
          registry: upplyprod.azurecr.io
          username: upplyprod
          password: ${{ secrets.UPPLY_ACR_PROD_PASSWORD }}

      - name: Build and push in registry
        uses: docker/build-push-action@v3
        if: inputs.artifact == null
        with:
          context: .
          tags: |
            upplydev.azurecr.io/${{ inputs.name }}:${{ inputs.version }}
            upplydev.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
            upplyquality.azurecr.io/${{ inputs.name }}:${{ inputs.version }}
            upplyquality.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
            upplypreprod.azurecr.io/${{ inputs.name }}:${{ inputs.version }}
            upplypreprod.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
            upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.version }}
            upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
          build-args: ${{ inputs.build-args }}
          push: true
          cache-from: type=registry,ref=upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
          cache-to: type=inline

      - name: Build and push as artifact
        uses: docker/build-push-action@v3
        if: inputs.artifact != null
        with:
          context: .
          tags: upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.version }}
          build-args: ${{ inputs.build-args }}
          push: false
          cache-from: type=registry,ref=upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
          cache-to: type=inline
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: inputs.artifact != null
        with:
          name: ${{ inputs.artifact }}
          path: /tmp/image.tar
          retention-days: 1
