name: Build
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
      build-args:
        required: true
        type: string
      context:
        required: false
        type: string
        default: "."
      artifact:
        required: false
        default: false
        type: boolean

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Login to ACR prod
        uses: docker/login-action@v2
        with:
          registry: upplyprod.azurecr.io
          username: upplyprod
          password: ${{ secrets.UPPLY_ACR_PROD_PASSWORD }}

      - name: Build and push in registry
        uses: docker/build-push-action@v3
        if: inputs.artifact == false
        with:
          context: ${{ inputs.context }}
          tags: |
            upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.version }}
            upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            ${{ inputs.build-args }}
          push: true
          cache-from: type=registry,ref=upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
          cache-to: type=inline

      - name: Build and push as artifact
        uses: docker/build-push-action@v3
        if: inputs.artifact == true
        with:
          context: ${{ inputs.context }}
          tags: upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.version }}
          build-args:  |
            GITHUB_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            ${{ inputs.build-args }}
          push: false
          cache-from: type=registry,ref=upplyprod.azurecr.io/${{ inputs.name }}:${{ inputs.tag }}
          cache-to: type=inline
          outputs: type=docker,dest=/tmp/${{ inputs.name }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: inputs.artifact == true
        with:
          name: ${{ inputs.name }}
          path: /tmp/${{ inputs.name }}.tar
          retention-days: 1
