name: PHP Pact publish
on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      provider:
        type: string
        required: true
      version:
        type: string
        required: true
      branch:
        type: string
        required: true

jobs:
  publish_pact:
    name: Publish Pact provider contract
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR prod
        uses: docker/login-action@v2
        with:
          registry: upplyprod.azurecr.io
          username: upplyprod
          password: ${{ secrets.UPPLY_ACR_PROD_PASSWORD }}

      - name: Pull image
        run: docker pull ${{ inputs.image }}
      
      - name: Echo openapi schema
        run: docker run -e APP_ENV=prod ${{ inputs.image }} bin/console nelmio:apidoc:dump | jq
      - name: Dump openapi schema
        run: docker run -e APP_ENV=prod ${{ inputs.image }} bin/console nelmio:apidoc:dump > openapi.json


      - name: Publish
        run: >
          docker run -v ${PWD}:/app -w "/app" pactfoundation/pact-cli
          pactflow publish-provider-contract
          openapi.json
          -b ${{ secrets.PACTFLOW_HOST  }}
          -k ${{ secrets.PACTFLOW_TOKEN }}
          --provider=${{ inputs.provider }}
          --provider-app-version=${{ inputs.version }}
          --branch=${{ inputs.branch }}
          --content-type=application/json
